# .github/workflows/main.yml
name: My Workflow

on:
  push:
    branches: [master]   # Change to your working branch name if needed
  workflow_dispatch:   # Allows manual triggering from the UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run a sample script
        run: echo "🎉 GitHub Actions is working!"
